name:                yaml-schema
version:             0.1.0.0
github:              "innayarantseva/yaml-schema"
license:             BSD3
author:              "Inna Yarantseva"
maintainer:          "innayarantseva@gmail.com"
copyright:           "2018 Inna Yarantseva"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/innayarantseva/yaml-schema#readme>

dependencies:
- base >= 4.7 && < 5
- text
- attoparsec

library:
  source-dirs: src

executables:
  yaml-schema-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yaml-schema

tests:
  yaml-schema-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yaml-schema
